apiVersion: apps/v1
kind: Deployment
metadata:
  name: park
  labels:
    app: park
spec:
  replicas: 1
  selector:
    matchLabels:
      app: park
  template:
    metadata:
      labels:
        app: park
    spec:
      containers:
      - name: park
        image: khalix/park:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: park
spec:
  selector:
    app: park
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: LoadBalancer